<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="15" passed="12">
  <reporter-output>
  </reporter-output>
  <suite name="nEXCITIZEN" duration-ms="458563" started-at="2019-12-19T10:20:41Z" finished-at="2019-12-19T10:28:20Z">
    <groups>
    </groups>
    <test name="nEXCITIZEN_TestCase1" duration-ms="458563" started-at="2019-12-19T10:20:41Z" finished-at="2019-12-19T10:28:20Z">
      <class name="com.TestCase.BirthCirtificateTestCase_Folder.BirthCirtificate_TestCase">
        <test-method status="PASS" signature="BithCirtificate_Tabhit()[pri:15, instance:com.TestCase.BirthCirtificateTestCase_Folder.BirthCirtificate_TestCase@13805618]" name="BithCirtificate_Tabhit" duration-ms="133758" started-at="2019-12-19T10:26:06Z" finished-at="2019-12-19T10:28:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BithCirtificate_Tabhit -->
      </class> <!-- com.TestCase.BirthCirtificateTestCase_Folder.BirthCirtificate_TestCase -->
      <class name="com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase">
        <test-method status="PASS" signature="Url_login()[pri:0, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase@5cb9f472]" name="Url_login" is-config="true" duration-ms="23432" started-at="2019-12-19T10:20:41Z" finished-at="2019-12-19T10:21:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Url_login -->
        <test-method status="FAIL" signature="Without_Username()[pri:1, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase@5cb9f472]" name="Without_Username" duration-ms="62074" started-at="2019-12-19T10:21:05Z" finished-at="2019-12-19T10:22:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[WithOut UserName Not Successfully login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: WithOut UserName Not Successfully login expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.PageObject.New_Registration.Login_Page.OnlyPassWordtest(Login_Page.java:48)
at com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase.Without_Username(Login_TestCase.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Without_Username -->
        <test-method status="FAIL" signature="Without_Password()[pri:2, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase@5cb9f472]" name="Without_Password" duration-ms="62054" started-at="2019-12-19T10:22:07Z" finished-at="2019-12-19T10:23:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[WithOut password Not Successfully login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: WithOut password Not Successfully login expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.PageObject.New_Registration.Login_Page.OnlyUserNametest(Login_Page.java:74)
at com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase.Without_Password(Login_TestCase.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Without_Password -->
        <test-method status="PASS" signature="Orginal_user_pass()[pri:3, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase@5cb9f472]" name="Orginal_user_pass" duration-ms="3667" started-at="2019-12-19T10:23:09Z" finished-at="2019-12-19T10:23:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Orginal_user_pass -->
      </class> <!-- com.TestCase.RegistrationandLoginTestCase_Folder.Login_TestCase -->
      <class name="com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase">
        <test-method status="PASS" signature="Hit_Application()[pri:4, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase@cb644e]" name="Hit_Application" duration-ms="5133" started-at="2019-12-19T10:23:13Z" finished-at="2019-12-19T10:23:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Hit_Application -->
        <test-method status="PASS" signature="Birth_Certificate()[pri:5, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase@cb644e]" name="Birth_Certificate" duration-ms="10410" started-at="2019-12-19T10:23:18Z" finished-at="2019-12-19T10:23:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Birth_Certificate -->
        <test-method status="PASS" signature="Death_Certificate_Tab()[pri:6, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase@cb644e]" name="Death_Certificate_Tab" duration-ms="10437" started-at="2019-12-19T10:23:28Z" finished-at="2019-12-19T10:23:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Death_Certificate_Tab -->
        <test-method status="PASS" signature="Trade_Licence()[pri:7, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase@cb644e]" name="Trade_Licence" duration-ms="10458" started-at="2019-12-19T10:23:39Z" finished-at="2019-12-19T10:23:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Trade_Licence -->
        <test-method status="PASS" signature="Property_Tax()[pri:8, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase@cb644e]" name="Property_Tax" duration-ms="11163" started-at="2019-12-19T10:23:49Z" finished-at="2019-12-19T10:24:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Property_Tax -->
        <test-method status="PASS" signature="Building_Plan()[pri:9, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase@cb644e]" name="Building_Plan" duration-ms="10605" started-at="2019-12-19T10:24:00Z" finished-at="2019-12-19T10:24:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Building_Plan -->
        <test-method status="PASS" signature="Building_Completion_Certificate()[pri:10, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase@cb644e]" name="Building_Completion_Certificate" duration-ms="11124" started-at="2019-12-19T10:24:11Z" finished-at="2019-12-19T10:24:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Building_Completion_Certificate -->
        <test-method status="FAIL" signature="Hording_and_Advertisement()[pri:11, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase@cb644e]" name="Hording_and_Advertisement" duration-ms="60226" started-at="2019-12-19T10:24:22Z" finished-at="2019-12-19T10:25:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Hording_and_Advertisement_Tab Hit expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Hording_and_Advertisement_Tab Hit expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.PageObject.New_Registration.Application_Status.Hording_and_Advertisement_Tab_Click(Application_Status.java:307)
at com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase.Hording_and_Advertisement(Application_TestCase.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Hording_and_Advertisement -->
        <test-method status="PASS" signature="Application_Details()[pri:12, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase@cb644e]" name="Application_Details" duration-ms="10499" started-at="2019-12-19T10:25:22Z" finished-at="2019-12-19T10:25:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Application_Details -->
        <test-method status="PASS" signature="Mutation_Certificate()[pri:13, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase@cb644e]" name="Mutation_Certificate" duration-ms="10632" started-at="2019-12-19T10:25:33Z" finished-at="2019-12-19T10:25:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Mutation_Certificate -->
        <test-method status="PASS" signature="Water_Supply()[pri:14, instance:com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase@cb644e]" name="Water_Supply" duration-ms="22823" started-at="2019-12-19T10:25:43Z" finished-at="2019-12-19T10:26:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Water_Supply -->
      </class> <!-- com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase -->
    </test> <!-- nEXCITIZEN_TestCase1 -->
  </suite> <!-- nEXCITIZEN -->
</testng-results>
