<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-E7S6MJ8" name="com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase" tests="2" failures="1" timestamp="19 Dec 2019 08:32:23 GMT" time="215.610" errors="0">
  <testcase name="Hit_Application" time="182.620" classname="com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Hording_and_Advertisement_Tab Hit expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Hording_and_Advertisement_Tab Hit expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.PageObject.Payment.Application_Status.Hording_and_Advertisement_Tab_Click(Application_Status.java:295)
at com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase.Hit_Application(Application_TestCase.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
    </failure>
  </testcase> <!-- Hit_Application -->
  <testcase name="Application_Details" time="32.990" classname="com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase"/>
</testsuite> <!-- com.TestCase.RegistrationandLoginTestCase_Folder.Application_TestCase -->
